[package]
name = "aoc-2024"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name = "historian-hysteria"
path = "src/day-1/historian-hysteria.rs"

[[bin]]
name = "red-nosed-reports"
path = "src/day-2/red-nosed-reports.rs"
